import { Inter } from "next/font/google";
import "./globals.css";
import Rainbow from "@/utils/rainbow/rainbowKit";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Rainbow>
          {children}
        </Rainbow>
        </body>
    </html>
  );
}
